name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "master"


jobs:
 
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:

        
      - name: create artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: .
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1